import React, { useEffect, useState } from "react";
import axios from "axios";
import { FaMoneyBillWave, FaArrowDown, FaArrowUp, FaSpinner } from "react-icons/fa";

const EmployeeSalary = () => {
  const [salaries, setSalaries] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const token = localStorage.getItem("token");

  const fetchSalary = async () => {
    try {
      setLoading(true);
      setError("");
      const res = await axios.get("http://127.0.0.1:5000/api/salary/my-salary", {
        headers: { Authorization: `Bearer ${token}` },
      });

      if (res.data?.success) {
        setSalaries(res.data.salaries || []);
      }
    } catch (err) {
      console.error("Error fetching salary history:", err);
      setError(err.response?.data?.error || "Failed to fetch personal salary history");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchSalary();
  }, [token]);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[400px] text-gray-500">
        <FaSpinner className="animate-spin text-3xl text-red-500 mb-2" />
        <p className="text-sm">Loading your salary slips...</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-100 p-6 md:p-8 space-y-6">
      {/* HEADING */}
      <div>
        <h1 className="text-3xl font-bold text-gray-800">My Salary History</h1>
        <p className="text-gray-500 text-sm mt-1">
          Inspect monthly payslips, basic allowances, and net breakdown
        </p>
      </div>

      {error && (
        <div className="bg-red-100 text-red-700 p-4 rounded-xl text-sm">
          {error}
        </div>
      )}

      {/* NO SALARY RECORDS */}
      {salaries.length === 0 ? (
        <div className="bg-white p-10 rounded-3xl shadow-sm border text-center">
          <FaMoneyBillWave className="text-5xl text-pink-500 mx-auto mb-3" />
          <h2 className="text-xl font-bold text-gray-700">No Salary Slips Available</h2>
          <p className="text-gray-500 text-xs mt-1">
            Your monthly payslips will be displayed here once generated by HR/Admin.
          </p>
        </div>
      ) : (
        <div className="space-y-6">
          {salaries.map((item) => {
            const net = item.netSalary || item.totalSalary;
            return (
              <div key={item._id} className="bg-white rounded-3xl shadow-sm border border-gray-200 p-6 md:p-8 space-y-6">
                {/* TOP HEADER */}
                <div className="flex justify-between items-center flex-wrap gap-4 pb-4 border-b">
                  <div>
                    <h2 className="text-2xl font-bold text-gray-800">
                      {item.month} {item.year}
                    </h2>
                    <p className="text-sm text-gray-500 mt-1">
                      Status:{" "}
                      <span
                        className={`font-bold ${
                          item.status === "Paid" ? "text-green-600" : "text-yellow-600"
                        }`}
                      >
                        {item.status}
                      </span>
                    </p>
                  </div>

                  <div className="bg-pink-50 border border-pink-200 px-6 py-3 rounded-2xl text-right">
                    <p className="text-xs text-gray-500 font-semibold uppercase">Net Take-Home</p>
                    <h2 className="text-2xl font-extrabold text-pink-600">${net?.toLocaleString()}</h2>
                  </div>
                </div>

                {/* DETAILS GRID */}
                <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4 text-sm">
                  <div className="bg-gray-50 p-4 rounded-2xl border">
                    <p className="text-xs text-gray-500 font-medium">Basic Salary</p>
                    <p className="text-lg font-bold text-gray-800 mt-1">${item.basicSalary}</p>
                  </div>

                  <div className="bg-blue-50 p-4 rounded-2xl border border-blue-100">
                    <div className="flex items-center gap-1.5 text-blue-700 text-xs font-semibold">
                      <FaArrowUp /> Allowances
                    </div>
                    <p className="text-lg font-bold text-blue-700 mt-1">+${item.allowances || 0}</p>
                  </div>

                  <div className="bg-green-50 p-4 rounded-2xl border border-green-100">
                    <div className="flex items-center gap-1.5 text-green-700 text-xs font-semibold">
                      <FaArrowUp /> Bonus
                    </div>
                    <p className="text-lg font-bold text-green-700 mt-1">+${item.bonus || 0}</p>
                  </div>

                  <div className="bg-red-50 p-4 rounded-2xl border border-red-100">
                    <div className="flex items-center gap-1.5 text-red-700 text-xs font-semibold">
                      <FaArrowDown /> Deductions
                    </div>
                    <p className="text-lg font-bold text-red-700 mt-1">-${item.deductions || 0}</p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};

export default EmployeeSalary;